<?php if($this->customizeBanner()): ?>
    <style>
        .greg-banner {
            background-color: #<?php echo $this->getBgColor() ?>;
        }
        .greg-banner .greg-banner__text,
        .greg-banner .greg-banner__link {
            color: #<?php echo $this->getFontColor() ?>
        }
    </style>
<?php endif; ?>

<?php if($this->render()): ?>
    <div class="greg-banner <?php if(!$this->getBannerPosition()): ?>greg-banner--bottom<?php endif; ?> clearfix std">
        <?php if($this->getBannerLink()): ?>
            <a class="greg-banner__link" href="<?php echo $this->getBannerLink() ?>" target="_blank"
            rel="noopener noreferrer">
                <p class="greg-banner__text"><?php echo $this->getBannerText();; ?></p>
            </a>
        <?php else: ?>
            <p class="greg-banner__text"><?php echo $this->getBannerText();; ?></p>
        <?php endif; ?>
    </div>
<?php endif; ?>